version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bernardo
      MYSQL_DATABASE: ObligatorioBD2023
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pbernardo"]
      interval: 15s
      timeout: 30s
      retries: 3

  blazor-app:
    image: funcionario_sano:latest
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 15 && dotnet YourBlazorApp.dll"
