version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: bernardo
      MYSQL_DATABASE: ObligatorioBD2023
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:6-alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "8013:8081"
    depends_on:
      - redis

  blazor-app:
    image: funcionario_sano:latest
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      redis-commander:
        condition: service_started
